backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "inhalt"
    label: "Webseite Texte & Medien"
    files:
      - label: "Startseite Inhalte"
        name: "startseite"
        file: "content.json"
        fields:
          - {label: "Willkommenstext", name: "willkommenstext", widget: "text"}
          - {label: "Aktions-Bild (Banner)", name: "aktions_bild", widget: "image"}
          - {label: "YouTube Video-ID (z.B. dQw4w9WgXcQ)", name: "youtube_id", widget: "string"}