backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "inhalt"
    label: "Webseite Texte & Medien"
    files:
      - label: "Aktuelle Aktion / News"
        name: "startseite"
        file: "content.json"
        fields:
          # NEU: "required: false" macht das Feld freiwillig!
          - {label: "Aktueller Text / Aktion", name: "willkommenstext", widget: "text", required: false, hint: "Was gibt es Neues?"}
          - {label: "Zusätzliches Foto", name: "aktions_bild", widget: "image", required: false, hint: "Optional"}
          - {label: "Zusätzliches YouTube Video-ID", name: "youtube_id", widget: "string", required: false, hint: "Optional. Nur die ID (z.B. dQw4w9WgXcQ)"}